workflows:
  expo-ios-testflight:
    name: Expo iOS → TestFlight (no EAS, uses prebuild)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        # Must exist in Codemagic UI:
        # - app_store_credentials: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
        # - certificate_credentials: CERTIFICATE_PRIVATE_KEY (and any other signing secrets you store)
        # - other: any extra vars your app needs (API keys, etc.)
        - app_store_credentials
        - certificate_credentials
        - other
      node: latest
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true

    scripts:
      - name: Install Bun
        script: |
          set -euo pipefail
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun --version

      - name: Install JS dependencies (mobile/)
        script: |
          set -euo pipefail
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          cd mobile
          bun install

      - name: Generate iOS project (Expo prebuild)
        script: |
          set -euo pipefail
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          cd mobile
          bunx expo prebuild --platform ios --clean --no-install

      - name: Install CocoaPods (mobile/ios)
        script: |
          set -euo pipefail
          cd mobile/ios
          pod install --repo-update

      - name: Initialize keychain
        script: |
          set -euo pipefail
          keychain initialize

      - name: Fetch signing files from App Store Connect (App Store profile)
        script: |
          set -euo pipefail
          # Get bundle id from app.json (avoids hardcoding)
          BUNDLE_ID="$(node -e "console.log(require('./mobile/app.json').expo.ios.bundleIdentifier)")"
          echo "BUNDLE_ID=$BUNDLE_ID"
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

      - name: Add certificates to keychain
        script: |
          set -euo pipefail
          keychain add-certificates

      - name: Bump build number (timestamp, always increasing)
        script: |
          set -euo pipefail
          BUILD_NUMBER="$(date +%Y%m%d%H%M)"
          echo "BUILD_NUMBER=$BUILD_NUMBER"

          # Find an Info.plist produced by prebuild and set CFBundleVersion
          PLIST_PATH="$(find mobile/ios -maxdepth 5 -name Info.plist | head -n 1 || true)"
          if [ -z "$PLIST_PATH" ]; then
            echo "ERROR: Info.plist not found under mobile/ios"
            find mobile/ios -maxdepth 4 -type f | head -n 200
            exit 1
          fi
          echo "Using plist: $PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$PLIST_PATH" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUMBER" "$PLIST_PATH"

      - name: Apply provisioning profiles to Xcode project
        script: |
          set -euo pipefail
          xcode-project use-profiles --warn-only

      - name: Build IPA (auto-detect workspace & scheme)
        script: |
          set -euo pipefail

          WORKSPACE="$(ls -1 mobile/ios/*.xcworkspace | head -n 1 || true)"
          if [ -z "$WORKSPACE" ]; then
            echo "ERROR: .xcworkspace not found in mobile/ios"
            ls -la mobile/ios || true
            exit 1
          fi
          echo "WORKSPACE=$WORKSPACE"

          # Extract first scheme from xcodebuild -list output (robust enough for CI)
          SCHEME="$(xcodebuild -list -workspace "$WORKSPACE" | awk '
            BEGIN{in_schemes=0}
            /Schemes:/{in_schemes=1; next}
            in_schemes && NF {gsub(/^[ \t]+|[ \t]+$/, "", $0); print $0; exit}
          ')"
          if [ -z "$SCHEME" ]; then
            echo "ERROR: Could not detect scheme from workspace."
            xcodebuild -list -workspace "$WORKSPACE" || true
            exit 1
          fi
          echo "SCHEME=$SCHEME"

          xcode-project build-ipa --workspace "$WORKSPACE" --scheme "$SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true


  expo-android-release:
    name: Expo Android (no EAS, uses prebuild)
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      groups:
        # Must exist in Codemagic UI:
        # - android_credentials: CM_KEYSTORE (base64), CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS_USERNAME, CM_KEY_ALIAS_PASSWORD
        # - other: any extra vars your app needs
        - android_credentials
        - other
      node: latest

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true

    scripts:
      - name: Install Bun
        script: |
          set -euo pipefail
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun --version

      - name: Install JS dependencies (mobile/)
        script: |
          set -euo pipefail
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          cd mobile
          bun install

      - name: Generate Android project (Expo prebuild)
        script: |
          set -euo pipefail
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          cd mobile
          bunx expo prebuild --platform android --clean --no-install

      - name: Set Android SDK location
        script: |
          set -euo pipefail
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/mobile/android/local.properties"

      - name: Set up keystore (from env group android_credentials)
        script: |
          set -euo pipefail
          echo "$CM_KEYSTORE" | base64 --decode > /tmp/keystore.keystore
          cat > "$FCI_BUILD_DIR/mobile/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_ALIAS_PASSWORD
          keyAlias=$CM_KEY_ALIAS_USERNAME
          storeFile=/tmp/keystore.keystore
          EOF

      - name: Build Android Release (APK)
        script: |
          set -euo pipefail
          cd mobile/android
          ./gradlew assembleRelease

    artifacts:
      - mobile/android/app/build/outputs/**/*.apk
      - mobile/android/app/build/outputs/**/*.aab
